### ISSUE TITLE
Airplane still not moving

### ISSUE THREAD

**Issue by ProfKenWord** [lian/msfs2020-go#15]
Hello,
in my case the Airplane on the map is still not moving (v 0.0.5). Stuck at Birmingham.
The displays of altitude, speed, etc. work.

Best regards
Raller

**Comment by lian** [comment]
i'm not able to reproduce that on my side.

obligatory checklist:
* ensure that you are really running v0.0.5, maybe download and unzip it again.
* maybe try a different browser. i only tested on chrome so far.

**Comment by ProfKenWord** [comment]
OK, i find out what is wrong. I followed your description in the readme and created an index.html file in the folder:

> _**change visualisation**
if you want to change how the webpage looks then copy and change index.html to the same folder as vfrmap.exe and relaunch the program._

I deleted the self made index.html and now it works and the airplane moves on the map.

So please check the code you entered for the index.html - it does not work!

**Comment by lian** [comment]
glad you figured it out.

the `change visualisation` section is only needed when you want to change/develop on the html/js part of the program without rebuilding the exe. it should work if you fetch the correct index.html.
