### ISSUE TITLE
False positive

### ISSUE THREAD

**Issue by Jekanyika** [lian/msfs2020-go#17]
Just to let you know I got a false positive from windows security.

![trojan](https://user-images.githubusercontent.com/70347278/91491705-59648400-e8ac-11ea-8f9c-2e2a40328e4b.PNG)

**Comment by lian** [comment]
thanks you for reporting! trying to figure this out. the scanners seems undeterministic when they like or hate the same exe/zip file.

https://github.com/lian/msfs2020-go/issues/14
