### ISSUE TITLE
Trojan:Win32/Email.A!cl detected in Windows Defender

### ISSUE THREAD

**Issue by ruku1143** [lian/msfs2020-go#18]
I have removed this application from my PC for the time being. It may be a false-positive, but I am unsure. This is with version v0.0.5.
![Annotation 2020-08-27 230000](https://user-images.githubusercontent.com/40524740/91499322-25dc2680-e8b9-11ea-81a1-4defbe4622bf.png)

**Comment by lian** [comment]
thanks you for reporting! trying to figure this out. the scanners seems undeterministic when they like or hate the same exe/zip file.

you could review and compile the program yourself though if you don't trust it.

lets move the discussion here: https://github.com/lian/msfs2020-go/issues/14
