### ISSUE TITLE
When I pan around the map, the camera snaps back to the plane.

### ISSUE THREAD

**Issue by aqua5am** [lian/msfs2020-go#19]
Is there any way to add functionality where you can pan around the map without it snapping back to the plane. It'd be cool to zoom in and look around the area.

Thanks so much, I love the app!

**Comment by lian** [comment]
@aqua5am you can click on the plane and then click the 'don't follow plane' button. OR you can toggle between follow and not follow with the ESC key.

**Comment by aqua5am** [comment]
@lian Oh that's perfect! Thank you so much :)
