### ISSUE TITLE
v0.0.2 causing jerky gameplay

### ISSUE THREAD

**Issue by RetromanIE** [lian/msfs2020-go#2]
Just tested this out. It runs the map fine, but the gameplay is very jerky when this plugin is running. As soon as i close it the game starts to run smoothly again.

**Comment by lian** [comment]
while i don't have this behavior myself, other people ran into this jerky gameplay with any addon that uses simconnect api to connect to msfs2020. asobo as acknowledged this issue and there is a good chance, for those affected, that a new msfs2020 update will just fix it. without any changes to the addons or in my case vfrmap.

https://www.reddit.com/r/MicrosoftFlightSim/comments/ic6pc0/asobo_has_acknowledged_simconnect_fps_issues/

**Comment by lian** [comment]
since v0.0.3, instead of every 100ms, it now fetches data every 200ms (5fps). for those running into the jerky gameplay behavior, this could already help. but its also good to expect this issue being solved for a MSFS2020 update soon.
