### ISSUE TITLE
Tip: Make it more iPad friendly

### ISSUE THREAD

**Issue by BertNienhuis** [lian/msfs2020-go#20]
With some easy code in top of index.html header you can make it more user friendly on the iPad as webapp. When you open the app inside the browser, you can than choose "Add to homescreen". When opened directly from the homescreen, all the controls like favorites and address bar are hidden and you will get a more native experience. 

Following code inside header. 

`<meta name="apple-mobile-web-app-capable" content="yes">`
`<meta name="apple-mobile-web-app-status-bar-style" content="black">`
`<meta name="apple-mobile-web-app-title" content="VFRMap">`

**Comment by lian** [comment]
nice!

i don't have an ipad to test. did/can you test this by adding it to the your index.html as described here: https://github.com/lian/msfs2020-go/tree/master/vfrmap#change-visualisation ?

happy to add it to next release then.

**Comment by BertNienhuis** [comment]
That was exactly what I did :-), I also made the font smaller. 1.2em I think. Great feature to experiment with the index.html

**Comment by lian** [comment]
cool, will add those header tags in next release.

was also planning to add a hide and + - button to the black header.

**Comment by BertNienhuis** [comment]
Awesome! That’s great. Just make sure the font is also a bit smaller, otherwise it will take more than one line. (Even in landscape mode). 

By the way; it feels running with VFRMap open that it introduces some stuttering. My fps doesn’t seem to be affected, but it feels stuttery. Do you experience the same? I saw something about performance regarding sim connect api in the upcoming patch. Hopefully that makes it more faster.

**Comment by lian** [comment]
lets wait if the new game update solves this.

also mentioned here https://github.com/lian/msfs2020-go/issues/2

if not, we could decrease how often we get new values from the sim. i read that this also solves the issue. currently we fetch a new data every 200ms, and see if there is new data every 100ms https://github.com/lian/msfs2020-go/blob/9e8bf05a27cda21fc64ddbf9c7a249deeeb5d222/vfrmap/main.go#L173-L174

**Comment by lian** [comment]
pushed the headers to master, will be in next release. thank you @BertNienhuis !

**Comment by BertNienhuis** [comment]
Great! I will test it tonight!

**Comment by zazaboeing** [comment]
> Great! I will test it tonight!

Hi Bert! Did you manage to make it work? Can you help us on #35 ? Thanks

**Comment by BertNienhuis** [comment]
> > Great! I will test it tonight!
> 
> Hi Bert! Did you manage to make it work? Can you help us on #35 ? Thanks

Yes it’s works perfectly. I think it’s already solved. You have too refer to the local network IP of the computer.
