### ISSUE TITLE
Night Mode?

### ISSUE THREAD

**Issue by FormBurden** [lian/msfs2020-go#22]
Would it be possible to add a night-mode feature so it's better on the eyes? Are you even able to since it seems that the data is pulled from a website such as OpenStreetMap? Anyway if because of that it makes it incredibly difficult if not impossible, what about filters or something? To layer over the map.

**Comment by lian** [comment]
that would be nice, and also unsure how easy that is. worst case we can add the overlay like you said. others in here also plan/want the night mode https://github.com/lian/msfs2020-go/issues/21

**Comment by ip999** [comment]
Hi, I've opened a little PR with a very simple change to give a dark mode map theme. hope that's ok? #23

**Comment by lian** [comment]
took @ip999 changes and added different plane color for night mode. will be in next release!

thank you @ip999 !
