### ISSUE TITLE
Access away from LAN

### ISSUE THREAD

**Issue by hankhank10** [lian/msfs2020-go#24]
I stream my game from a remote server.

Looking through the code, it looks like at present this only works over LAN but I presume there's no reason this couldn't be opened up to be available on a port that can be accessed remotely?

**Comment by lian** [comment]
it already listens on `0.0.0.0:9000`. meaning any device that can ready your machine's ip is able to open it. if you want to change the port, then start the program with `-listen 0.0.0.0:8000` argument to listen on port 8000 for example.
