### ISSUE TITLE
Access from other machines on the local network?

### ISSUE THREAD

**Issue by Kabouik** [lian/msfs2020-go#26]
Thanks for this nice tool! I was wondering if there could be an option to serve the map somewhere else than localhost so that other machines on the local network could access it, possibly with some confirmation prompt on the host for security reasons, but else with just the user setting up permissions in the first place?

I believe it would make vfrmap much more flexible, and also a nice and open alternative to those mobile applications. Trusted people could even follow flights on remote machines, provided they use something like Zerotier; note this would also be useful for people who use cloud computing to run MFS 2020.

**Comment by lian** [comment]
you can already access it from any device on your network if you know your ip. then just browse to `http://your-ip:9000`

the program accepts a `-listen` argument upon start. default is `-listen 0.0.0.0:9000` meaning to listen on any network interface (localhost, your wifi, and ethernet). you could change that to restrict it to localhost only. but i changed the default to 0.0.0.0 so people can easily access it from their tablets etc.

**Comment by Kabouik** [comment]
Awesome, thanks. I haven't found a way to access the map yet on my machine running MFS 2020 and connected to the same Zerotier network, despite working ping, but I suppose this is some hidden setting in Zerotier or Windows Network that I haven't found yet. I'm trying to access the map from a Linux machine, mixing OSes in Zerotier probably doesn't help either.

**Comment by lian** [comment]
yea that must be a zerotier issue or config issue around that though. access from other machines in your local network should just work.
