### ISSUE TITLE
Is it possible to turn off teleport?

### ISSUE THREAD

**Issue by RegenCoE** [lian/msfs2020-go#27]
Hello lian and thank you for this amazing tool.

I was tinkering around a bit with it - works amazingly well. I own a URL at which I created a webforward pointing to my external IP address. In my router I forwarded port 9000 to the machine running MSFS - so now if i go to http://[URL]:9000 I can view the map from anywhere in the world - even my phone or tablet.

That also means I could in theory broadcast this URL to friends or use it for streaming so people can watch my flight in a different tab if they want to - however I noticed there's also a function that allows me (or anyone accessing the map) to click anywhere on the map and then teleport the plane to that location - which of course would be terrible if someone did that during a stream - and also could be viewed as cheating ;)

Would it be possible to include a function to disable the "teleport" function ?

Cheers,

RegenCoE

**Comment by lian** [comment]
good suggestion :)

i could add a command argument to turn off teleport. will try for next release.

**Comment by RegenCoE** [comment]
Awesome, thanks alot!

**Comment by lian** [comment]
https://github.com/lian/msfs2020-go/releases v0.0.7 includes the `-disable-teleport` command argument.
