### ISSUE TITLE
[Suggestion] Would it be able to add a button to center the aircraft position and one to un-center or un-snap it, so i can move the map more freely?

### ISSUE THREAD

**Issue by Pschirki** [lian/msfs2020-go#28]
Danke für das super Programm!!! Das wertet den MSFS um 200% auf!!👏

It would be great if i could move the map without aut-centering the aircraft position so it would be easier to look for special places while zoomed in. 

Keep up the great work!!

**Comment by ip999** [comment]
Press escape 🙂

**Comment by lian** [comment]
like @ip999 said. press escape key to toggle between follow and unfollow. OR click on your plane and press 'don't follow plane'.
