### ISSUE TITLE
Is there a way to use it with my own API key?

### ISSUE THREAD

**Issue by Rimpelstullchen** [lian/msfs2020-go#29]
Hello Lian

Thanks for your great work!

I have compiled your version 0.0.1 and 0.0.2 with go and tried to use my own google api key

cmd > vfrmap.exe -api-key [mykey]

it just works for a second and then I get an javascript error in my browser
do I something wrong?
can I implement my key direct in your code somewhere?

your version 0.0.6 works really fine.
but google satellite data together with MSFS is just wow

**Comment by lian** [comment]
hey, using the old version with -api-key should 'just work'. maybe if you have the detailed error that javascript chrome dev tools output it would be easier to debug.

but this projects doesn't support that old version anymore, so i'm going to close the issue here.
