### ISSUE TITLE
[Suggestion] Using Browser in IOS or Android.

### ISSUE THREAD

**Issue by Nuzair46** [lian/msfs2020-go#3]
Is there a way to view the map in a phone's browser in the same network?

**Comment by Raging-Beard** [comment]
Yes, get the IP of you computer. In a command prompt (Win key, type "cmd", hit enter) type "ipconfig".
Where it says IPv4 address is the IP you need, something like 192.168.*.*

In a browser on your device simply go to whatever your IP is followed by 9000.
For example... http://192.168.*.*:9000

**Comment by lian** [comment]
@Raging-Beard thank you for helping @rednek46!

since release v0.0.2 it's exactly how @Raging-Beard described. if you happen to still be on v0.0.1 then update :)

**Comment by Nuzair46** [comment]
cool thanks.
