### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by knightvision1980** [lian/msfs2020-go#30]
Hi,

Many times when i connect and start ingame a flight.
My consoles says something going wrong look at the console.
when i check the console cmd, i see some text talking about closes 1001 socket (go away) message.
so the browser starts the page and i can click the button on low left and i see the map but after a few seconds its disconnecting.
How can it be resolved?

**Comment by lian** [comment]
`i can click the button on low left` that sounds like an old version. can you try the latest version from here https://github.com/lian/msfs2020-go/releases ?

**Comment by knightvision1980** [comment]
> 
> 
> `i can click the button on low left` that sounds like an old version. can you try the latest version from here https://github.com/lian/msfs2020-go/releases ?

Hahaha no i have the newst already, and yes i can click below button, the map loads but after a few second its get stuck with a error message. when i check console i see 1001 socket or seomthing and message go away

**Comment by lian** [comment]
which browser do you use? can you try a different browser? i use chrome. but have seen others running this on their ipad so that should work too.
