### ISSUE TITLE
Windows Defender detects a Trojan in the executable

### ISSUE THREAD

**Issue by BravoFoxMike** [lian/msfs2020-go#32]
Windows Defender won't allow me to run the exe, saying it has a Trojan.

**Comment by leejbarker82** [comment]
Same for me...

**Comment by lian** [comment]
reopend the old issue here: https://github.com/lian/msfs2020-go/issues/14

was hoping i solved this. when i uploaded v0.0.7 last night all virustotal scanners (including microsoft) were happy.

https://www.virustotal.com/gui/file/3d7dc453123b2c8bf0c27dfa03ae9d477347318b4e953711c6ff5f20e047b819/detection
