### ISSUE TITLE
Virus detected in latest release V0.0.7

### ISSUE THREAD

**Issue by baobab67** [lian/msfs2020-go#33]
When I try to download the zip file at https://github.com/lian/msfs2020-go/releases/download/v0.0.7/vfrmap-win64-v0.0.7.zip
Edge Browser says - "Couldn't download - Virus detected"

**Comment by lian** [comment]
its a false-positive :( please see https://github.com/lian/msfs2020-go/issues/14

**Comment by Bi0force1** [comment]
I was playing yesterday using v0.0.7 and mid flight Windows 10 deleted the .exe and now it won't let me download it again  :(

**Comment by lian** [comment]
@Bi0force1 i think you can tell windows to restore that file and allow it in the future.

edit: `mid flight Windows 10 deleted the .exe` haha, thats equally funny and sad :joy:
