### ISSUE TITLE
Cannot open on iPad

### ISSUE THREAD

**Issue by zazaboeing** [lian/msfs2020-go#35]
Hi! 
Tried several things, but couldn't open it on iPad. Can you make a more clear readme on how to make it happen!?

Thanks a lot for such a great plugin!

**Comment by Jonas1898** [comment]
Same problem here, do we have to configure something else for using on iPad?

**Comment by lian** [comment]
can you explain what issue you see? i don't have an ipad to test. it might be related to this? https://github.com/lian/msfs2020-go/issues/20

can you test v0.0.6 and see if it works. if so, i have to revert changes from https://github.com/lian/msfs2020-go/issues/20

**Comment by Bi0force1** [comment]
I have an iPad i can test on, im just not familiar with the steps to run it.  Do I launch the .exe on my PC, then go to localhost:9000 on my iPad?

**Comment by zazaboeing** [comment]
> can you explain what issue you see? i don't have an ipad to test. it might be related to this? #20
> 
> can you test v0.0.6 and see if it works. if so, i have to revert changes from #20

I just can't open the **localhost** _or_ with **IP** on the ipad browser. It doesn't connect. In the PC it's ok!

**Comment by lian** [comment]
oh you tried localhost on the ipad? it needs to be your gaming pc ip instead of localhost, like described in the readme here https://github.com/lian/msfs2020-go/tree/master/vfrmap#run

### run
* run vfrmap.exe
* browse to http://localhost:9000
* or to `http://<computer-ip>:9000`


depending on your network it would look something like this once you know your gaming pc ip `http://192.168.0.10:9000/`

**Comment by zazaboeing** [comment]
Hi Lian, thanks for the help, but yes, tried all the above steps. All possible combinations. And yes, the game is running with a flight.

**Comment by lian** [comment]
@zazaboeing no clue. have you tried v0.0.6? doesn't work with it either?

**Comment by zazaboeing** [comment]
Got it working Lian! Turned out I was trying with my Internet IP, not my Physical IP. Thanks, its a GREAT tool!

**Comment by lian** [comment]
perfect!

@Jonas1898 hope you had the same mixup

**Comment by Jonas1898** [comment]
I am so sorry to ask, but what IP do I have to use? Physical IP? Where can I find that? Thanks so much!

**Comment by lian** [comment]
@Jonas1898 your local ip. https://www.groovypost.com/howto/microsoft/windows-7/find-your-local-ip-address-windows-7-cmd/
