### ISSUE TITLE
Trojan:Win32/Emali.A! Found by Microsoft Security

### ISSUE THREAD

**Issue by Raul-WA4TPR** [lian/msfs2020-go#36]
Trojan:Win32/Emali.A! Found by Microsoft Security

**Comment by MuppetOwl** [comment]
Can also confirm same detection. Most likely false but still strange as the previous version had no issues. Only latest one. 0.0.7

**Comment by lian** [comment]
lets move discussion here https://github.com/lian/msfs2020-go/isues/14

@MuppetOwl yea, no idea why. yesterday, this exact file passed all scanners here https://www.virustotal.com/gui/file/3d7dc453123b2c8bf0c27dfa03ae9d477347318b4e953711c6ff5f20e047b819/detection

today Microsoft scanner says no, but said yes yesterday. fml

**Comment by lian** [comment]
great, i hit 'retry' on https://www.virustotal.com/gui/file/3d7dc453123b2c8bf0c27dfa03ae9d477347318b4e953711c6ff5f20e047b819/detection

and now it shows all green again. as if microsoft scanner just can make up its mind.

**Comment by Bi0force1** [comment]
i can confirm that v0.0.7 was throwing false errors yesterday and early this morning and now i am able to download without issue.
