### ISSUE TITLE
exe wont launch since 0.0.3 - simconnect error

### ISSUE THREAD

**Issue by mckooter** [lian/msfs2020-go#37]
I am fairly sure this is something on my end, as I waited to see if anyone else reported but there has been a ton of releases and no one has complained, but since 0.0.3 which changed to openstreetmap my exe opens then closes. If I launch it from CMD I get the following:

```
msfs2020-go/vfrmap
  readme: https://github.com/lian/msfs2020-go/blob/master/vfrmap/README.md
  issues: https://github.com/lian/msfs2020-go/issues
  version: v0.0.7 (2020-09-05_04:33:49)

panic: SimConnect_Open error: -2147467259 The operation completed successfully.

goroutine 1 [running]:
main.main()
        /users/lian/prj/go/lian/msfs2020-go/vfrmap/main.go:115 +0x2125
```

I know this isn't an issue with the software itself as others would be having, but can anyone advise on what I have done wrong here. I am quite new to all of this but it was working at one point :)

Thanks,

**Comment by mckooter** [comment]
figured it out. had an issue on my end. sorry for opening. It's amazing how you never find your issue until you start asking about it

**Comment by lian** [comment]
what was it? very curious :)

**Comment by mckooter** [comment]
Well. I was having issues for a long while, not sure if it was related. but it turns out rather embarrassingly it was because this time I was not in an active flight. So it had nothing to connect to I think. 

I feel like I had tested that before but I launched MSFS but apparently didn't start the flight today when I was trying to launch the app. Once I did it connected. Sorry :)
