### ISSUE TITLE
Window always in front?

### ISSUE THREAD

**Issue by mensa84** [lian/msfs2020-go#41]
Hello,

is it possible that that windows is always visible in front of FS 2020? Or is it only for additional displays?

**Comment by Bi0force1** [comment]
You might want to look at AlwaysOnTop, which is a 1 line code for AutoHotKey that lets you make any window stick to the top.

https://www.labnol.org/software/tutorials/keep-window-always-on-top/5213/

**Comment by lian** [comment]
since this is "just" your browser window, the app itself can't enforce that. could try various windows tools to enforce a window to be always on top.
