### ISSUE TITLE
Strange behavior when multiple users open the map

### ISSUE THREAD

**Issue by mrpowershell** [lian/msfs2020-go#44]
I don't know if this is known yet, but I had something very strange moments with the VFR map yesterday.
I have used the mod a few times now, it worked fine, but yesterday I wanted to test how it is when
I share the mapserver so that external people can open the map as well. (port forward) This works so far,
but as soon as a second or third person opens the card, Flight Simulator goes crazy. The following is
happens:

Sim is running active flight:

Second person opens the card : Plane is teleported randomly or SIM crashes completely.

New flight is started and the map is opened by 2 or 3 persons:

Plane starts somewhere in the world or SIM crashes.

Is this known? This has not happened every time, but quite regularly.
__________________________________________________________________________

**Comment by lian** [comment]
can you try to start it with `vfrmap.exe -disable-teleport` argument and see if it still happens? maybe your users just smashed the teleport button?

i haven't tried it with other users. but had it open on my desktop, laptop and phone on the same time, without any observed issues.

**Comment by mrpowershell** [comment]
I will try that. I let you know if that fixed the issue.

**Comment by mrpowershell** [comment]
can be closed. i just got the info that they used the teleport function. didnt know that that is an feature. will disable it with your command.
