### ISSUE TITLE
flight sim goes crazy

### ISSUE THREAD

**Issue by mattinjersey** [lian/msfs2020-go#46]
Hello I am using Flight Sim to fly the plane externally. I am using the Autopilot with heading control using the keyboard. Sometimes the FlightSim goes crazy and the heading starts rotating and cannot stop it. Seems to be related to this map program. Thanks Matt

**Comment by lian** [comment]
will try to reproduce, but expect for teleport, the program doesn't 'SET' any values in the sim. it only reads the displayed values. there is still a chance that only reading those could somehow cause your issue, but it would be very weird.

**Comment by mattinjersey** [comment]
OK. I should try it without using the program (just Flight Simulator). Maybe it is just a bug with Flight Simulator. Thanks.

**Comment by mattinjersey** [comment]
Yes I confirmed that its a bug in Flight Simulator, unrelated to your program. Thanks!

**Comment by lian** [comment]
good to hear! you they solve your issue in a next patch. or you find a workaround
