### ISSUE TITLE
Ability to use Google Maps with personal API key

### ISSUE THREAD

**Issue by sttovo** [lian/msfs2020-go#47]
Would you be able to restore the functionality to allow Google Maps integration for those with their own API key?

Thank you! This is a great product!

**Comment by sttovo** [comment]
I failed to add that I'm using the original index.html with my own key added, but I'd like to be able to use all the latest features.

**Comment by lian** [comment]
sorry gmap isn't supported anymore. see discussion here https://github.com/lian/msfs2020-go/issues/9
