### ISSUE TITLE
Backlog/Kanban board

### ISSUE THREAD

**Issue by andrewlilley-ux** [lian/msfs2020-go#50]
Hi, would you want to work from a Kanban board with an icebox, backlog etc? There are lots of feature requests and plans, and if I'm to help with the user interface, it would be useful to know which features will be developed before I put the effort in to design them. We could any free one, but here are some that claim to integrate with Github https://stackshare.io/kanban-for-github-issues

**Comment by andrewlilley-ux** [comment]
I just noticed Github has this built in, called Projects :) Do you want to set this up?

**Comment by lian** [comment]
i'm a bit tight on time currently, sorry. hoping to pick this up soon.
