### ISSUE TITLE
black terminal stuck at Kitty Hawk

### ISSUE THREAD

**Issue by rlego** [lian/msfs2020-go#6]
Connected to Flight Simulator!
SIMCONNECT_RECV_ID_OPEN KittyHawk

**Comment by lian** [comment]
that looks correct. now browse to http://localhost:9000 and you should see the map in your browser

**Comment by rlego** [comment]
yes, map is loading corectly, but shows this

![image](https://user-images.githubusercontent.com/70224659/91210494-96dedb00-e70d-11ea-869e-fba79411ed0b.png)

**Comment by lian** [comment]
hm, can you start it with `-verbose` argument? it should print out each received flight sim packet in the terminal then. if there are none, its weird and i haven't encountered this then.

when you made the screenshot, your plane was already flying right?

**Comment by lian** [comment]
closing. you can comment to re-open

**Comment by rlego** [comment]
shortcut with -verbose works flawless. There is only "for development puposes only" watermark. Can i setup google map api to remove that? Is there any option to open map on ipad or android (same wifi network)

**Comment by lian** [comment]
please update to the latest version, it uses openstreetmap now and doesn't require an api key anymore. if you know your computer ip you can just browse to http://<your-computer-ip>:9000 from any device in your network. the ipad too
