### ISSUE TITLE
waypoint HDG in game

### ISSUE THREAD

**Issue by plop28** [lian/msfs2020-go#70]
Hello,
First, thanks for this addon, it works well and it is very useful. 
I have a question about setting a waypoint on the vfr map, is there a way to have heading information in game ? 
I can place the waypoint on the map, but I have no informations about it in game. 
Is this plugin able to provide this ?

**Comment by lczapla02** [comment]
Hi,

Not yet, I am limited by Microsoft Flight Simulator SDK... But hopefully I
will in future at some point.

**Comment by plop28** [comment]
OK then, thanks for your reply.
