### ISSUE TITLE
Google Maps option

### ISSUE THREAD

**Issue by RetromanIE** [lian/msfs2020-go#9]
Would it be possible to get google maps back? Maybe as an option we must select ourselves and provide our own API code etc.
The satellite views with label overlays on google maps is very good for this type of thing.

**Comment by lian** [comment]
yea satellite views with label overlays are awesome on google maps.

yesterday morning when i needed to solve the google maps api key cost generating issue i initially wanted to support both. allow users to set their own gmap api key (so i don't have to pay for their usage) and allow openstreetmap.

but for this i would have to implement any behavior or drawing on the map twice. once using the google maps javascript sdk, and once using leafletjs (for openstreetmap). for every current and upcoming behavior. with the teleport marker this would already be annoying, but once i add waypoints etc, doing that for both feels too much effort. also testing both map types all the time :)

hope you can relate. tried to find a gmap api key sponsor but failed. so for now openstreetmap (leafletjs) it is.

back in the days google also allowed to fetch tile images, that would just work with leafletjs. good old free gmap days :sweat:

**Comment by RetromanIE** [comment]
> yea satellite views with label overlays are awesome on google maps.
> 
> yesterday morning when i needed to solve the google maps api key cost generating issue i initially wanted to support both. allow users to set their own gmap api key (so i don't have to pay for their usage) and allow openstreetmap.
> 
> but for this i would have to implement any behavior or drawing on the map twice. once using the google maps javascript sdk, and once using leafletjs (for openstreetmap). for every current and upcoming behavior. with the teleport marker this would already be annoying, but once i add waypoints etc, doing that for both feels too much effort. also testing both map types all the time :)
> 
> hope you can relate. tried to find a gmap api key sponsor but failed. so for now openstreetmap (leafletjs) it is.
> 
> back in the days google also allowed to fetch tile images, that would just work with leafletjs. good old free gmap days 😓

I do understand. Once they fix the simconnect issue in MSFS this is something i will just autoload beside flight sim, its such a useful tool. Thanks
